# Render Deployment Configuration

services:
  - type: web
    name: Bot
    env: python
    plan: free
    runtime: python3.8
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    gitCloneSubpath: .
